FROM --platform=linux/amd64 golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod ./
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /controller ./cmd/controller

FROM scratch
COPY --from=build /controller /controller
EXPOSE 8080
ENTRYPOINT ["/controller"]
