FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /agent ./cmd/agent

FROM scratch
COPY --from=build /agent /agent
ENTRYPOINT ["/agent"]
