server {
  listen 8080;
  root /usr/share/nginx/html;
  location /api/ { proxy_pass http://controller:8080; }
  location /auth/ { proxy_pass http://controller:8080; }
  location / { try_files $uri $uri/ /index.html; }
}
