server {
  listen 8080;
  root /usr/share/nginx/html;
  location /api/ { proxy_pass http://controller:8080; }
  location /auth/ { proxy_pass http://controller:8080; }
  location /capture/ {
    proxy_pass http://controller:8080;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_read_timeout 3900s;
  }
  location / { try_files $uri $uri/ /index.html; }
}
