import React, { useEffect, useState } from "react";
import { createRun, createSearch, createTarget, deleteTarget, getRun, listRuns, listTargets } from "./api.js";
import { toRunConfig, toSearchConfig } from "./run-form.js";
import { presets } from "./record-utils.js";

const initial = { type:"model", url:"http://model.internal:8000/v1/chat/completions", model:"", apiKey:"", profileName:"", profileId:"", prompt:presets.coding.prompt, maxTokens:presets.coding.maxTokens, cachePolicy:"mixed", variationPercent:"30", mode:"vu", vus:"10", rps:"100", duration:"60", maxErrorPercent:"2", maxP95Millis:"2000", startLoad:"5", maxLoad:"40" };
const updateForm = (set) => (e) => set(v => ({...v, [e.target.name]:e.target.value, ...( ["url","model","apiKey"].includes(e.target.name) ? {profileId:""} : {})}));

function Profiles({ profiles, form, setForm, refresh, error }) {
  const select = (e) => { const p = profiles.find(v => v.id === e.target.value); setForm(v => p ? {...v, profileId:p.id, profileName:p.name, type:p.type, url:p.url, model:p.model, apiKey:""} : {...v, profileId:""}); };
  const save = async () => { try { if (!form.profileName || !form.url || !form.model) throw new Error("프로필 이름, URL, 모델명을 입력하세요."); await createTarget({name:form.profileName,type:"model",url:form.url,model:form.model,api_key:form.apiKey}); await refresh(); } catch(e) { error(e.message); } };
  return <section className="panel"><h3>등록 모델</h3><div className="grid"><label>등록 모델 선택<select value={form.profileId} onChange={select}><option value="">직접 입력</option>{profiles.filter(p=>p.type === "model").map(p=><option key={p.id} value={p.id}>{p.name} · {p.model}</option>)}</select></label><label>프로필 이름<input name="profileName" value={form.profileName} onChange={updateForm(setForm)} placeholder="예: LM Studio Qwen" /></label><label>API 키<input name="apiKey" type="password" value={form.apiKey} onChange={updateForm(setForm)} placeholder={form.profileId ? "등록된 키 사용 중" : "선택 사항"} /></label></div><button type="button" onClick={save}>현재 값으로 모델 등록</button>{form.profileId && <button className="danger" type="button" onClick={async()=>{await deleteTarget(form.profileId); setForm(v=>({...v,profileId:""})); refresh();}}>선택 모델 삭제</button>}</section>;
}

export default function App() {
 const [form,setForm]=useState(initial),[profiles,setProfiles]=useState([]),[runs,setRuns]=useState([]),[run,setRun]=useState(null),[auto,setAuto]=useState(false),[error,setError]=useState(""); const update=updateForm(setForm); const refresh=()=>listTargets().then(setProfiles).catch(e=>setError(e.message)); useEffect(()=>{refresh();listRuns().then(setRuns).catch(e=>setError(e.message));},[]); useEffect(()=>{if(!run||run.status!=="queued"&&run.status!=="running")return;const id=setInterval(()=>getRun(run.id).then(setRun),1000);return()=>clearInterval(id)},[run]);
 const start=async()=>{try{let target;if(form.profileId)target={id:form.profileId};else target=await createTarget({name:form.profileName||form.model||"Model API",type:form.type,url:form.url,model:form.model,api_key:form.apiKey}); const payload={...form,targetId:target.id}; setRun(auto?await createSearch(toSearchConfig(payload)):await createRun(toRunConfig(payload)));}catch(e){setError(e.message)}};
 return <main className="shell"><aside><h1>Load Observatory</h1></aside><div className="content"><header><div><h2>부하 테스트</h2><p>등록 모델을 선택하면 URL·모델명·인증 키를 재입력할 필요가 없습니다.</p></div></header>{error&&<p className="error">{error}</p>}<Profiles profiles={profiles} form={form} setForm={setForm} refresh={refresh} error={setError}/><section className="panel"><label>대상 URL<input name="url" value={form.url} onChange={update}/></label><label>모델명<input name="model" value={form.model} onChange={update}/></label><label>프롬프트<textarea name="prompt" value={form.prompt} onChange={update}/></label><label>최대 토큰<input name="maxTokens" type="number" value={form.maxTokens} onChange={update}/></label><label>VU<input name="vus" type="number" value={form.vus} onChange={update}/></label><label>시간(초)<input name="duration" type="number" value={form.duration} onChange={update}/></label><label>캐시<select name="cachePolicy" value={form.cachePolicy} onChange={update}><option value="mixed">혼합</option><option value="reuse">활용</option><option value="bypass">우회</option></select></label><button type="button" onClick={()=>setAuto(v=>!v)}>{auto?"자동 탐색":"수동 테스트"}</button><button onClick={start}>테스트 시작</button></section><section className="panel"><h3>최근 실행</h3>{runs.map(r=><button key={r.id} onClick={()=>setRun(r)}>{r.id} · {r.status}</button>)}{run&&<pre>{JSON.stringify(run.result||run,null,2)}</pre>}</section></div></main>;
}
