import React, { useEffect, useState } from "react";
import { cancelSearch, createRun, createSearch, createTarget, getHealth, getRun, getSearch, listRuns } from "./api.js";
import { toRunConfig, toSearchConfig } from "./run-form.js";
import { getVerdict, milliseconds, rate } from "./results.js";

const initial = { type: "model", url: "http://model.internal:8000/v1/chat/completions", model: "", prompt: "Implement a small Go HTTP API with validation and tests.", maxTokens: "4096", mode: "vu", vus: "10", rps: "100", duration: "60", maxErrorPercent: "2", maxP95Millis: "2000", startLoad: "5", maxLoad: "40" };
const labels = { test: "부하 테스트", records: "테스트 기록", monitor: "모니터링" };
const Metric = ({ label, value, tone = "" }) => <section className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong></section>;

function Details({ run }) {
  if (!run) return <section className="panel"><h3>실행 결과</h3><p className="muted">수동 또는 자동 테스트를 시작하면 상세 분석 결과가 표시됩니다.</p></section>;
  const result = run.result || {}; const total = result.total || (result.successes || 0) + (result.failures || 0); const verdict = getVerdict(run); const latency = result.latency || {}; const ttft = result.ttft || {}; const tokens = result.tokens || {};
  return <section className="details"><section className={`panel verdict ${verdict.status}`}><div><h3>{verdict.status === "stable" ? "안정 구간" : verdict.status === "at-risk" ? "위험 구간" : "판정 대기"}</h3><p>{verdict.recommendation}</p></div><span>오류 기준 {run.config.max_error_percent ?? 2}% · P95 기준 {milliseconds(run.config.max_p95_millis ?? 2000)}</span></section>
    <section className="panel"><h3>실행 설정</h3><div className="config-summary"><span>부하 <b>{run.config.mode === "rps" ? `${run.config.rps} RPS` : `${run.config.vus} VU`}</b></span><span>시간 <b>{run.config.duration_seconds}초</b></span><span>최대 출력 <b>{run.config.max_tokens || "—"} 토큰</b></span></div>{run.config.prompt && <p className="prompt-preview">프롬프트: {run.config.prompt}</p>}</section>
    <section className="panel"><h3>운영 요약</h3><div className="metrics"><Metric label="총 요청" value={total || "—"} /><Metric label="성공률" value={rate(result.successes || 0, total)} tone="good" /><Metric label="처리량" value={result.throughput_rps ? `${result.throughput_rps.toFixed(1)} RPS` : "—"} /><Metric label="오류율" value={rate(result.failures || 0, total)} tone="bad" /></div></section>
    <section className="panel"><h3>지연 분석</h3><div className="distribution"><Distribution title="응답 시간" values={latency} /><Distribution title="첫 토큰 도착 (TTFT)" values={ttft} /></div></section>
    {tokens.completion > 0 && <section className="panel"><h3>모델 출력 분석</h3><div className="metrics"><Metric label="입력 토큰" value={tokens.prompt} /><Metric label="출력 토큰" value={tokens.completion} /><Metric label="추론 토큰" value={tokens.reasoning || "—"} /><Metric label="전체 출력 속도" value={`${tokens.output_per_second?.toFixed(1) || 0} tok/s`} /></div></section>}
    <section className="panel"><h3>시간별 추세</h3><table><thead><tr><th>경과</th><th>요청</th><th>성공</th><th>실패</th><th>P95</th></tr></thead><tbody>{(result.timeline || []).length ? result.timeline.map((point) => <tr key={point.second}><td>{point.second + 1}초</td><td>{point.requests}</td><td>{point.successes}</td><td>{point.failures}</td><td>{milliseconds(point.p95_millis)}</td></tr>) : <tr><td colSpan="5">추세 데이터가 없습니다.</td></tr>}</tbody></table></section>
    <section className="split"><section className="panel"><h3>응답 상태</h3><table><tbody>{Object.entries(result.status_counts || {}).length ? Object.entries(result.status_counts).map(([status, count]) => <tr key={status}><td>HTTP {status}</td><td>{count}</td></tr>) : <tr><td>데이터 없음</td></tr>}</tbody></table></section><section className="panel"><h3>최근 오류</h3>{(result.errors || []).length ? <ul className="errors">{result.errors.map((error, index) => <li key={`${error}-${index}`}>{error}</li>)}</ul> : <p className="muted">오류가 없습니다.</p>}</section></section>
  </section>;
}

function Distribution({ title, values }) { return <div><h4>{title}</h4><div className="distribution-values"><span>최소 <b>{milliseconds(values.min_millis)}</b></span><span>평균 <b>{milliseconds(values.avg_millis)}</b></span><span>P50 <b>{milliseconds(values.p50_millis)}</b></span><span>P95 <b>{milliseconds(values.p95_millis)}</b></span><span>P99 <b>{milliseconds(values.p99_millis)}</b></span><span>최대 <b>{milliseconds(values.max_millis)}</b></span></div></div>; }

function AutoSearchPanel({ form, update, search, onStart, onCancel, busy }) {
  const steps = search?.run_ids?.length || 0;
  return <section className="panel auto"><div className="section-title"><div><h3>자동 용량 탐색</h3><p className="muted">시작 부하부터 2배씩 올리고, 위험 구간에서는 이진 탐색으로 최대 안정 부하를 찾습니다.</p></div><span className={`status ${search?.status || "idle"}`}>{search?.status || "대기"}</span></div>
    <div className="grid"><label>시작 부하<input name="startLoad" type="number" min="1" value={form.startLoad} onChange={update} required /></label><label>최대 부하<input name="maxLoad" type="number" min="1" value={form.maxLoad} onChange={update} required /></label><label>단계별 실행 시간 (초)<input name="duration" type="number" min="1" max="3600" value={form.duration} onChange={update} required /></label></div>
    {search ? <div className="search-progress"><span>완료 단계 <b>{steps}</b></span><span>다음 부하 <b>{search.next_load || "—"}</b></span><span>최대 안정 <b>{search.recommended_load || search.stable_load || "—"}</b></span><p>{search.message || "현재 단계를 실행 중입니다."}</p></div> : <button type="button" onClick={onStart} disabled={busy}>자동 탐색 시작</button>}
    {search?.status === "running" && <button type="button" className="danger" onClick={onCancel}>자동 탐색 중지</button>}
  </section>;
}

export default function App() {
  const [page, setPage] = useState("test"); const [form, setForm] = useState(initial); const [run, setRun] = useState(null); const [runs, setRuns] = useState([]); const [selected, setSelected] = useState(null); const [search, setSearch] = useState(null); const [health, setHealth] = useState(null); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const refreshRuns = async () => { try { setRuns(await listRuns()); } catch (err) { setError(err.message); } };
  useEffect(() => { if (!run || run.status === "completed") return undefined; const timer = setInterval(async () => { try { setRun(await getRun(run.id)); } catch (err) { setError(err.message); } }, 1000); return () => clearInterval(timer); }, [run]);
  useEffect(() => { if (!search || search.status !== "running") return undefined; const timer = setInterval(async () => { try { setSearch(await getSearch(search.id)); } catch (err) { setError(err.message); } }, 1000); return () => clearInterval(timer); }, [search]);
  useEffect(() => { if (page === "records") refreshRuns(); }, [page]);
  useEffect(() => { if (page !== "monitor") return undefined; const refresh = async () => { try { setHealth(await getHealth()); } catch (err) { setError(err.message); } }; refresh(); const timer = setInterval(refresh, 2000); return () => clearInterval(timer); }, [page]);
  const makeTarget = () => createTarget({ name: form.type === "model" ? "Model API" : "Web endpoint", type: form.type, url: form.url, model: form.model });
  const start = async (event) => { event.preventDefault(); setSubmitting(true); setError(""); try { const target = await makeTarget(); setRun(await createRun(toRunConfig({ ...form, targetId: target.id }))); } catch (err) { setError(err.message); } finally { setSubmitting(false); } };
  const startAuto = async () => { setSubmitting(true); setError(""); try { const target = await makeTarget(); setSearch(await createSearch(toSearchConfig({ ...form, targetId: target.id }))); } catch (err) { setError(err.message); } finally { setSubmitting(false); } };
  const stopAuto = async () => { try { setSearch(await cancelSearch(search.id)); } catch (err) { setError(err.message); } };
  return <main className="shell"><aside><h1>Load Observatory</h1><nav>{Object.entries(labels).map(([key, label]) => <button key={key} className={page === key ? "active" : ""} onClick={() => { setPage(key); setError(""); }}>{label}</button>)}</nav><p className="system">폐쇄망 대상만 허용</p></aside><div className="content"><header><div><h2>{labels[page]}</h2><p>처리량, 지연, 오류와 모델 토큰을 함께 분석합니다.</p></div><span className="online">● Controller online</span></header>{error && <p className="error" role="alert">{error}</p>}
    {page === "test" && <><form className="panel" onSubmit={start}><h3>수동 테스트 설정</h3><div className="grid"><label>대상 유형<select name="type" value={form.type} onChange={update}><option value="model">GPU 모델 API</option><option value="web">웹 API</option></select></label><label className="wide">대상 URL<input name="url" value={form.url} onChange={update} required /></label>{form.type === "model" && <><label className="wide">모델명<input name="model" value={form.model} onChange={update} placeholder="qwen/qwen3.6-35b-a3b" required /></label><label>출력 최대 토큰<input name="maxTokens" type="number" min="1" max="1000000" value={form.maxTokens} onChange={update} required /></label><label className="wide">프롬프트<textarea name="prompt" value={form.prompt} onChange={update} required /></label></>}<label>부하 방식<select name="mode" value={form.mode} onChange={update}><option value="vu">동시 사용자 (VU)</option><option value="rps">요청률 (RPS)</option></select></label>{form.mode === "vu" ? <label>동시 사용자<input name="vus" type="number" min="1" max="500" value={form.vus} onChange={update} required /></label> : <label>요청률<input name="rps" type="number" min="1" max="2000" value={form.rps} onChange={update} required /></label>}<label>실행 시간 (초)<input name="duration" type="number" min="1" max="3600" value={form.duration} onChange={update} required /></label><label>허용 오류율 (%)<input name="maxErrorPercent" type="number" min="0" max="100" step="0.1" value={form.maxErrorPercent} onChange={update} required /></label><label>허용 P95 지연 (ms)<input name="maxP95Millis" type="number" min="1" value={form.maxP95Millis} onChange={update} required /></label></div><button disabled={submitting}>{submitting ? "생성 중..." : "수동 테스트 시작"}</button></form><AutoSearchPanel form={form} update={update} search={search} onStart={startAuto} onCancel={stopAuto} busy={submitting} /><Details run={run} /></>}
    {page === "records" && <><section className="panel"><div className="section-title"><h3>실행 기록</h3><button className="small" onClick={refreshRuns}>새로고침</button></div><table><thead><tr><th>ID</th><th>상태</th><th>부하</th><th>성공률</th><th>P95</th><th>판정</th></tr></thead><tbody>{runs.length ? runs.map((item) => { const verdict = getVerdict(item); const total = item.result?.total || (item.result?.successes || 0) + (item.result?.failures || 0); return <tr className="selectable" key={item.id} onClick={() => setSelected(item)}><td>{item.id}</td><td>{item.status}</td><td>{item.config.mode === "rps" ? `${item.config.rps} RPS` : `${item.config.vus} VU`}</td><td>{rate(item.result?.successes || 0, total)}</td><td>{milliseconds(item.result?.latency?.p95_millis ?? item.result?.p95_millis)}</td><td>{verdict.status}</td></tr>; }) : <tr><td colSpan="6">기록이 없습니다.</td></tr>}</tbody></table></section>{selected && <Details run={selected} />}</>}
    {page === "monitor" && <section className="panel"><h3>실시간 상태</h3><div className="metrics"><Metric label="Controller" value={health?.controller_online ? "온라인" : "확인 중"} tone="good" /><Metric label="Agent" value={health ? (health.agent_online ? "온라인" : "오프라인") : "확인 중"} /><Metric label="대기 실행" value={health?.queued_runs ?? "—"} /><Metric label="실행 중" value={health?.running_runs ?? "—"} /></div><p className="muted">2초마다 자동 갱신됩니다.</p></section>}</div></main>;
}
