import React, { useEffect, useState } from "react";
import { cancelSearch, createRun, createSearch, createTarget, deleteTarget, getHealth, getRun, getSearch, listRuns, listTargets } from "./api.js";
import { toRunConfig, toSearchConfig } from "./run-form.js";
import { policyText, presets } from "./record-utils.js";
import { getVerdict, milliseconds, rate } from "./results.js";

const initial = { type: "model", url: "http://model.internal:8000/v1/chat/completions", model: "", prompt: presets.coding.prompt, maxTokens: presets.coding.maxTokens, cachePolicy: "mixed", variationPercent: "30", mode: "vu", vus: "10", rps: "100", duration: "60", maxErrorPercent: "2", maxP95Millis: "2000", startLoad: "5", maxLoad: "40" };
const emptyProfile = { name: "", type: "model", url: "http://model.internal:8000/v1/chat/completions", model: "", apiKey: "" };
const Metric = ({ label, value }) => <section className="metric"><span>{label}</span><strong>{value}</strong></section>;
const loadText = (run) => run.config.mode === "rps" ? `${run.config.rps} RPS` : `${run.config.vus} VU`;

function Details({ run }) {
  if (!run) return <section className="panel empty">실행 기록을 선택하면 상세 분석이 표시됩니다.</section>;
  const result = run.result || {}; const total = result.total || (result.successes || 0) + (result.failures || 0);
  return <section className="details"><section className="panel"><h3>실행 상세</h3><div className="metrics"><Metric label="성공률" value={rate(result.successes || 0, total)} /><Metric label="P95" value={milliseconds(result.latency?.p95_millis ?? result.p95_millis)} /><Metric label="처리량" value={result.throughput_rps ? `${result.throughput_rps.toFixed(1)} RPS` : "-"} /></div><p className="muted">{loadText(run)} · {run.config.duration_seconds}초 · 최대 출력 {run.config.max_tokens} 토큰 · {policyText(run)}</p><p className="prompt-preview">{run.config.prompt}</p></section></section>;
}

function TestSettings({ form, update, profiles, selectedProfileId, selectProfile }) {
  return <div className="grid">
    <label className="wide">등록된 대상<select value={selectedProfileId} onChange={(e) => selectProfile(e.target.value)}><option value="">새 대상 직접 입력</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name} — {profile.model || profile.url}</option>)}</select></label>
    <label>대상 유형<select name="type" value={form.type} onChange={update}><option value="model">GPU 모델 API</option><option value="web">웹 API</option></select></label><label className="wide">대상 URL<input name="url" value={form.url} onChange={update} required /></label>
    {form.type === "model" && <><label className="wide">모델명<input name="model" value={form.model} onChange={update} required /></label><label>출력 최대 토큰<input name="maxTokens" type="number" min="1" max="1000000" value={form.maxTokens} onChange={update} required /></label><label className="wide">프롬프트<textarea name="prompt" value={form.prompt} onChange={update} required /></label><div className="preset-row">{Object.entries(presets).map(([key, preset]) => <button type="button" className="preset" key={key} onClick={() => { update({ target: { name: "prompt", value: preset.prompt } }); update({ target: { name: "maxTokens", value: preset.maxTokens } }); }}>{key === "short" ? "짧은 응답" : key === "coding" ? "코딩 작업" : "긴 출력"}</button>)}</div></>}
    <label>캐시 정책<select name="cachePolicy" value={form.cachePolicy} onChange={update}><option value="mixed">혼합: 반복 + 변형</option><option value="reuse">캐시 활용: 반복 요청</option><option value="bypass">캐시 우회: 모두 변형</option></select></label>{form.cachePolicy === "mixed" && <label>변형 요청 비율 (%)<input name="variationPercent" type="number" min="0" max="100" value={form.variationPercent} onChange={update} /></label>}
    <label>부하 방식<select name="mode" value={form.mode} onChange={update}><option value="vu">동시 사용자 (VU)</option><option value="rps">요청률 (RPS)</option></select></label><label>{form.mode === "rps" ? "요청률" : "동시 사용자"}<input name={form.mode === "rps" ? "rps" : "vus"} type="number" min="1" value={form.mode === "rps" ? form.rps : form.vus} onChange={update} /></label><label>실행 시간 (초)<input name="duration" type="number" min="1" value={form.duration} onChange={update} /></label><label>허용 오류율 (%)<input name="maxErrorPercent" type="number" min="0" max="100" value={form.maxErrorPercent} onChange={update} /></label><label>허용 P95 (ms)<input name="maxP95Millis" type="number" min="1" value={form.maxP95Millis} onChange={update} /></label>
  </div>;
}

function Profiles({ profiles, profile, update, save, remove }) {
  return <><section className="panel"><h3>모델/대상 등록</h3><p className="muted">인증키는 저장 후 다시 표시되지 않습니다. 테스트에서 등록된 대상을 선택하면 저장된 인증키가 사용됩니다.</p><div className="grid"><label>표시 이름<input name="name" value={profile.name} onChange={update} required /></label><label>대상 유형<select name="type" value={profile.type} onChange={update}><option value="model">GPU 모델 API</option><option value="web">웹 API</option></select></label><label className="wide">대상 URL<input name="url" value={profile.url} onChange={update} required /></label>{profile.type === "model" && <label className="wide">모델명<input name="model" value={profile.model} onChange={update} required /></label>}<label className="wide">인증키 (선택)<input name="apiKey" type="password" autoComplete="new-password" value={profile.apiKey} onChange={update} /></label></div><button onClick={save}>등록</button></section><section className="panel"><h3>등록된 대상</h3>{profiles.length === 0 ? <p className="muted">등록된 대상이 없습니다.</p> : <table><thead><tr><th>이름</th><th>유형</th><th>모델</th><th>URL</th><th>인증키</th><th /></tr></thead><tbody>{profiles.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.type === "model" ? "모델" : "웹"}</td><td>{item.model || "-"}</td><td>{item.url}</td><td>{item.has_api_key ? "저장됨" : "없음"}</td><td><button className="danger" onClick={() => remove(item)}>삭제</button></td></tr>)}</tbody></table>}</section></>;
}

function Records({ runs, choose }) { return <section className="panel"><h3>테스트 기록</h3><table><thead><tr><th>실행</th><th>유형</th><th>부하</th><th>캐시</th><th>성공률</th><th>P95</th><th>판정</th></tr></thead><tbody>{runs.map((item) => { const result = item.result || {}; const total = result.total || (result.successes || 0) + (result.failures || 0); return <tr className="selectable" key={item.id} onClick={() => choose(item)}><td>{item.id}</td><td>{item.search_id ? "자동 탐색" : "수동"}</td><td>{loadText(item)}</td><td>{policyText(item)}</td><td>{rate(result.successes || 0, total)}</td><td>{milliseconds(result.latency?.p95_millis ?? result.p95_millis)}</td><td>{getVerdict(item).status}</td></tr>; })}</tbody></table></section>; }

export default function App() {
  const [page, setPage] = useState("test"), [mode, setMode] = useState("manual"), [form, setForm] = useState(initial), [run, setRun] = useState(null), [runs, setRuns] = useState([]), [search, setSearch] = useState(null), [health, setHealth] = useState(null), [error, setError] = useState(""), [profiles, setProfiles] = useState([]), [profile, setProfile] = useState(emptyProfile), [selectedProfileId, setSelectedProfileId] = useState("");
  const refreshProfiles = () => listTargets().then(setProfiles).catch((err) => setError(err.message));
  const update = (e) => { if (["type", "url", "model"].includes(e.target.name)) setSelectedProfileId(""); setForm((value) => ({ ...value, [e.target.name]: e.target.value })); };
  const updateProfile = (e) => setProfile((value) => ({ ...value, [e.target.name]: e.target.value }));
  const refresh = () => listRuns().then(setRuns).catch((err) => setError(err.message));
  useEffect(() => { refreshProfiles(); }, []);
  useEffect(() => { if (page === "records") refresh(); if (page === "profiles") refreshProfiles(); }, [page]);
  useEffect(() => { if (!run || ["completed", "cancelled"].includes(run.status)) return; const id = setInterval(() => getRun(run.id).then(setRun).catch((e) => setError(e.message)), 1000); return () => clearInterval(id); }, [run]);
  useEffect(() => { if (!search || search.status !== "running") return; const id = setInterval(() => getSearch(search.id).then(setSearch).catch((e) => setError(e.message)), 1000); return () => clearInterval(id); }, [search]);
  useEffect(() => { if (page === "monitor") getHealth().then(setHealth).catch((e) => setError(e.message)); }, [page]);
  const selectProfile = (id) => { setSelectedProfileId(id); const item = profiles.find((value) => value.id === id); if (item) setForm((value) => ({ ...value, type: item.type, url: item.url, model: item.model || "" })); };
  const saveProfile = async () => { try { if (!profile.name || !profile.url || (profile.type === "model" && !profile.model)) throw new Error("이름, URL, 모델명을 입력하세요."); await createTarget({ name: profile.name, type: profile.type, url: profile.url, model: profile.model, api_key: profile.apiKey }); setProfile(emptyProfile); await refreshProfiles(); } catch (err) { setError(err.message); } };
  const removeProfile = async (item) => { try { await deleteTarget(item.id); if (selectedProfileId === item.id) setSelectedProfileId(""); await refreshProfiles(); } catch (err) { setError(err.message); } };
  const start = async () => { try { const targetId = selectedProfileId || (await createTarget({ name: form.type === "model" ? "Model API" : "Web endpoint", type: form.type, url: form.url, model: form.model })).id; if (mode === "automatic") setSearch(await createSearch(toSearchConfig({ ...form, targetId }))); else setRun(await createRun(toRunConfig({ ...form, targetId }))); } catch (err) { setError(err.message); } };
  const titles = { test: "부하 테스트", records: "테스트 기록", monitor: "모니터링", profiles: "모델 등록" };
  return <main className="shell"><aside><h1>Load Observatory</h1><nav>{[["test", "부하 테스트"], ["records", "테스트 기록"], ["monitor", "모니터링"], ["profiles", "모델 등록"]].map(([id, label]) => <button className={page === id ? "active" : ""} key={id} onClick={() => setPage(id)}>{label}</button>)}</nav></aside><div className="content"><header><div><h2>{titles[page]}</h2><p>캐시 상황을 반영한 실제 사용 패턴으로 한계를 측정합니다.</p></div><span className="online">● Controller online</span></header>{error && <p className="error">{error}</p>}{page === "test" && <><section className="mode-tabs"><button className={mode === "manual" ? "active" : ""} onClick={() => setMode("manual")}>수동 테스트</button><button className={mode === "automatic" ? "active" : ""} onClick={() => setMode("automatic")}>자동 용량 탐색</button></section><section className="panel"><h3>{mode === "manual" ? "한 번의 부하를 측정합니다" : "최대 안정 부하를 자동으로 찾습니다"}</h3><TestSettings form={form} update={update} profiles={profiles} selectedProfileId={selectedProfileId} selectProfile={selectProfile} />{mode === "automatic" && <div className="grid auto-fields"><label>시작 부하<input name="startLoad" type="number" min="1" value={form.startLoad} onChange={update} /></label><label>최대 부하<input name="maxLoad" type="number" min="1" value={form.maxLoad} onChange={update} /></label></div>}<button onClick={start}>{mode === "manual" ? "테스트 시작" : "자동 탐색 시작"}</button>{search && <p className="search-progress">{search.status} · {search.message} · 권장 최대 {search.recommended_load || search.stable_load || "-"}</p>}{search?.status === "running" && <button className="danger" onClick={() => cancelSearch(search.id).then(setSearch)}>중지</button>}</section><Details run={run} /></>}{page === "records" && <><Records runs={runs} choose={setRun} /><Details run={run} /></>}{page === "monitor" && <section className="summary"><Metric label="Controller" value={health?.controller_online ? "온라인" : "확인 중"} /><Metric label="Agent" value={health?.agent_online ? "온라인" : "오프라인"} /><Metric label="대기" value={health?.queued_runs ?? "-"} /><Metric label="실행 중" value={health?.running_runs ?? "-"} /></section>}{page === "profiles" && <Profiles profiles={profiles} profile={profile} update={updateProfile} save={saveProfile} remove={removeProfile} />}</div></main>;
}
